CodeMyst/pastemyst

views/api-docs.dt
=> Added rate limits and expiry dates to api docs

public/style/index.css, public/style/source/index.scss, views/layout.dt
=> Added footer

views/api-docs.dt
=> Changed api url in api docs

public/style/index.css, public/style/source/index.scss, source/app.d, views/layout.dt
=> Displaying number of pastes in the footer

public/style/index.css, public/style/source/index.scss, views/layout.dt
=> Copyright symbol isn't so small anymore

views/layout.dt
=> Page is now indexable by search engines

views/layout.dt
=> Page title is now a link to the home page

public/style/index.css, public/style/source/index.scss, views/layout.dt, views/paste.dt
* Better highlighted the content
* Title and navigation combined into one codeblock
* Moved id and createdAt at the bottom
Closes #30
=> Restyled the paste page

public/style/index.css, public/style/source/index.scss, views/layout.dt
=> Made the footer responsive

public/scripts/main.js, views/index.dt
=> Removed reCAPTCHA

public/scripts/main.js, public/style/index.css, public/style/source/index.scss, views/index.dt
=> Added a plain text editor

views/index.dt, views/layout.dt
=> Using absolute paths for style, script, etc.

views/index.dt, views/layout.dt, views/paste.dt
=> Fixed SEO titles

source/app.d, source/pastemyst.d, views/api-docs.dt
=> Able to get paste without /paste?id= url

public/style/index.css, public/style/source/index.scss
=> Disabled resizing on the plain editor

source/pastemyst.d, views/paste.dt
=> Shows when a paste expires (if it expires)

public/style/index.css, public/style/source/index.scss, views/layout.dt
=> Showing the version in the page navigation

README.md
=> Note added that you need to add a language column

public/style/index.css, public/style/source/index.scss
=> Made the pastemyst content font smaller on mobile

public/style/index.css, public/style/source/index.scss
=> Using tab-size 4

CHANGELOG.md, public/style/index.css, public/style/source/index.scss, views/layout.dt
=> Traditional styled navbar.

CHANGELOG.md, views/index.dt
=> Removed "Create a new PasteMyst" text

public/style/index.css, public/style/source/index.scss, views/layout.dt, views/paste.dt, views/profile.dt
=> Better paste title styling

public/style/index.css, public/style/source/index.scss, source/web.d, views/paste.dt
=> Able to view raw paste content

frontend/src/styles/pages/_home.scss, frontend/src/views/index.pug
=> Added title input field

frontend/src/styles/components/_button.scss, frontend/src/styles/components/_tooltip.scss, frontend/src/styles/pages/_home.scss, frontend/src/styles/styles.scss, frontend/src/views/index.pug
=> Added the create paste button

api/.gitignore, api/.vscode/launch.json, api/.vscode/tasks.json, api/dub.json, api/dub.selections.json, api/source/app.d, api/source/pastemyst/data/dataFile.d, api/source/pastemyst/data/expiresIn.d, api/source/pastemyst/data/package.d, api/source/pastemyst/data/paste.d, api/source/pastemyst/db.d, api/source/pastemyst/rest/package.d, api/source/pastemyst/rest/paste.d, api/source/pastemyst/rest/root.d
=> Inserting pastes into the DB

api/source/pastemyst/data/dataFile.d, api/source/pastemyst/data/expiresIn.d, api/source/pastemyst/db.d, api/source/pastemyst/encoding/base36.d, api/source/pastemyst/encoding/package.d, api/source/pastemyst/rest/paste.d, api/source/pastemyst/rest/root.d
=> Generating IDs for pastes

api/source/pastemyst/data/paste.d, api/source/pastemyst/rest/paste.d
=> Added titles to pastes

frontend/src/scripts/api/expireOptions.ts, frontend/src/scripts/api/paste.ts, frontend/src/scripts/app.ts, frontend/src/scripts/data/paste.ts, frontend/src/styles/pages/_home.scss, frontend/src/views/index.pug
=> Creating pastes from the frontend

api/source/pastemyst/conv/package.d, api/source/pastemyst/conv/to.d, api/source/pastemyst/data/expiresIn.d, api/source/pastemyst/data/paste.d, api/source/pastemyst/rest/paste.d
=> Properly converting ExpiresIn enum to string

frontend/src/styles/components/_footer.scss, frontend/src/styles/pages/_home.scss, frontend/src/views/components/footer.pug, frontend/src/views/home.pug
=> Made the paste options and footer responsive

frontend/src/scripts/api/paste.ts, frontend/src/scripts/app.ts, frontend/src/scripts/views/home.ts, frontend/src/scripts/views/paste.ts, frontend/src/styles/_variables.scss, frontend/src/styles/components/_highlight.scss, frontend/src/styles/pages/_home.scss, frontend/src/styles/pages/_paste.scss, frontend/src/styles/styles.scss, frontend/src/views/components/dropdown.pug, frontend/src/views/components/header.pug, frontend/src/views/components/navigation.pug, frontend/src/views/home.pug, frontend/src/views/index.pug, frontend/src/views/paste.pug, frontend/tslint.json
=> Added the paste page

api/source/app.d, frontend/src/scripts/api/api.ts, frontend/src/scripts/views/paste.ts
=> Viewing raw pastes

api/dub.json, api/dub.selections.json, api/source/pastemyst/auth/exceptions.d, api/source/pastemyst/auth/github.d, api/source/pastemyst/auth/package.d, api/source/pastemyst/db.d, api/source/pastemyst/rest/paste.d, frontend/src/scripts/api/auth.ts, frontend/src/scripts/api/paste.ts
=> If logged in the owner ID gets attached to a paste

api/source/pastemyst/auth/bearer.d, api/source/pastemyst/auth/github.d, api/source/pastemyst/auth/package.d, frontend/src/scripts/renderer/renderer.ts, frontend/src/scripts/views/home.ts, frontend/src/scripts/views/profile.ts
=> Disallow opening the profile page if not logged in

api/source/app.d, api/source/pastemyst/auth/bearer.d, api/source/pastemyst/auth/github.d, api/source/pastemyst/db.d, api/source/pastemyst/rest/package.d, api/source/pastemyst/rest/user.d, frontend/src/scripts/api/user.ts, frontend/src/scripts/router/router.ts, frontend/src/scripts/views/profile.ts, frontend/src/styles/_variables.scss, frontend/src/styles/pages/_profile.scss, frontend/src/views/profile.pug
=> Showing all user's pastes

api/source/pastemyst/auth/bearer.d, api/source/pastemyst/auth/exceptions.d, api/source/pastemyst/auth/github.d, api/source/pastemyst/auth/package.d, api/source/pastemyst/rest/paste.d, api/source/pastemyst/rest/user.d, frontend/src/scripts/api/paste.ts, frontend/src/scripts/views/home.ts, frontend/src/scripts/views/paste.ts
=> Private pastes

frontend/src/scripts/views/profile.ts
=> Reloading the page after logging out

frontend/src/scripts/renderer/renderer.ts, frontend/src/scripts/renderer/view.ts, frontend/src/scripts/views/home.ts, frontend/src/scripts/views/paste.ts
=> Fixed codemirror

frontend/src/scripts/time/time.ts, frontend/src/scripts/views/paste.ts, frontend/src/scripts/views/profile.ts, frontend/src/styles/pages/_profile.scss, frontend/src/views/profile.pug
=> Showing when a paste expires on the profile page

api/source/app.d, api/source/pastemyst/conv/to.d, api/source/pastemyst/db/db.d, api/source/pastemyst/db/package.d, api/source/pastemyst/db/paste.d
=> Deleting expired pastes

frontend/.vscode/tasks.json, frontend/src/scripts/views/paste.ts, frontend/src/scripts/views/profile.ts
=> Showing time in lowercase

frontend/src/scripts/time/time.ts
=> Time difference works with weeks now as well

public/style/components/scrollbar.css, public/style/main.css
=> custom scrollbar

public/scripts/main.js, public/style/components/navigation.css
Implemented highlighting on toggleable options using the 3rd color scheme as discussed in #256.
I wasn't able to properly setup Docker on my machine, so these changes are untested in a built scenario, but I did my best at testing in-browser. It would be great if someone could properly test the changes to verify they work.
=> Highlighted toggleable options, closes #256

public/style/components/markdownRendered.css, public/style/pages/paste.css
=> better markdown styling

public/scripts/pages/paste.js
=> fixed editor selection offset

public/scripts/pages/history.js, public/scripts/pages/paste.js
=> when copying links added the protocol as well

public/scripts/components/pastyEditor.js, public/scripts/pages/history.js, public/scripts/pages/paste.js, public/style/libs/codemirror-myst.css, public/style/libs/codemirror-solarized.css
=> fixed html mode

data/languages.json, public/scripts/components/pastyEditor.js, public/scripts/pages/history.js, public/scripts/pages/paste.js
=> fixed jsx mode

public/style/components/codemirror.css, public/style/components/scrollbar.css
=> better codemirror scrollbars

public/style/components/scrollbar.css, views/error.dt
=> better page when an internal error occurs

.gitignore, source/app.d
=> logging internal errors to a file

source/pastemyst/paste/create.d
=> returning plain text if autodetect errors

views/paste.dt
=> html isnt rendered anymore in markdown pastes

public/docs/index.md
=> added api libraries to api docs

source/pastemyst/data/package.d, source/pastemyst/data/version.d, views/apiDocs/index.dt, views/baseLayout.dt, views/createUser.dt, views/editPaste.dt, views/embed.dt, views/error.dt, views/header.dt, views/history.dt, views/home.dt, views/paste.dt, views/profile.dt, views/publicProfile.dt, views/settings.dt, views/userData.dt
=> versioning asset files

public/scripts/pages/paste.js
=> fixed highlighting lines

public/style/components/markdownRendered.css
=> fixed hljs overflow in markdown

public/docs/user.md, source/pastemyst/rest/user.d
=> added supporterLength and contributor to api

source/pastemyst/rest/user.d, source/pastemyst/web/login.d, source/pastemyst/web/user.d
=> fixed username search

public/scripts/pages/profile.js, views/profile.dt, views/publicProfile.dt
=> optimized the deletes at value on a profile

public/style/libs/codemirror-solarized.css, public/style/theme-solarized.css
=> improved solarized theme

public/docs/data.md
This issue addresses a fix for issue 322.
=> Fixed incorrect information (Fixes #322)

public/style/components/markdownRendered.css
=> fixed wrapping of inline code blocks

public/scripts/main.js, views/baseLayout.dt
- no more flickering
closes #259
=> loading a page with a theme should be faster now

public/scripts/components/pastyEditor.js, public/style/components/pastyEditor.css, views/components/pastyEditor.dt
=> reordering pasties

README.md, public/docs/index.md, public/style/components/markdownRendered.css
* added v and typescript libs to docs
closes #337 
closes #336
=> specified how to provide the auth header

.gitignore, dub.json, dub.selections.json, source/app.d, source/pastemyst/db/package.d, source/pastemyst/db/zips.d, source/pastemyst/web/paste.d, views/components/pasteHeader.dt
=> added downloading pastes as a zip

source/app.d
=> redirecting api trailing slashes

README.md, public/docs/index.md
=> Fixes issue 348

.gitattributes, dub.json, lib/windows/scrypt.lib
=> built scrypt.lib for windows

source/pastemyst/web/paste.d
=> Check for zip extension before trimming

public/style/components/markdownRendered.css
=> unbreakable words will now wrap in markdown

public/style/components/markdownRendered.css
=> tables now properly scroll on overflow

public/docs/index.md
=> added pastemystgo and fixed pastemyst.v in docs

public/docs/data.md
This pull request closes #360 
Here's a preview of how the site looks:
=> Mention about Uri encoding

README.md, public/docs/index.md
added MystPaste.NET (closes #374)
added pastemyst-cpp
added pastemyst.java (closes #375
=> added a few libs to docs

source/pastemyst/paste/create.d
=> checking for extensions when autodetecting

.gitmodules, backend/data/languages.yml, backend/dub.json, backend/dub.selections.json, backend/source/pastemyst/api/v3/data.d, backend/source/pastemyst/data/files.d, backend/source/pastemyst/model/language.d, backend/source/pastemyst/model/package.d
=> reading the languages.yml and serving with api

frontend/package-lock.json, frontend/package.json, frontend/src/Home.svelte, frontend/src/components/BigSelect.svelte, frontend/src/components/Editor.svelte, frontend/src/components/Header.svelte, frontend/src/components/Select.svelte, frontend/src/components/TextInput.svelte
=> fullsize language select

frontend/package-lock.json, frontend/package.json, frontend/src/components/BigSelect.svelte, frontend/src/components/Editor.svelte, frontend/src/components/IndentSelect.svelte
=> selecting the indent unit and amount

public/scripts/pages/home.js, source/pastemyst/auth/session.d, source/pastemyst/web/login.d
=> fixed login bug because cookie was set to strict

views/decrypt.dt, views/home.dt
=> encrypt password fields are proper password fields

source/pastemyst/paste/package.d, source/pastemyst/paste/stats.d, views/paste.dt
=> showing some paste stats

source/pastemyst/data/config.d, views/baseLayout.dt
=> possible to add html to head tags through config
